[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200